version: '3'
services:

  app:
    build: .
    environment:
      - ETHERPAD_VERSION=1.6.2
      - ETHERPAD_ADMIN_PASSWORD=supersecret
      - USERID=1000
      - GROUPID=1000
    ports:
      - "9001:9001"
    volumes:
      - "~/srv/epl/var:/opt/etherpad-lite/var"
      - "~/srv/epl/node_modules:/opt/etherpad-lite/node_modules"
    restart: always
